apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    name: lb-service
spec:
  type: LoadBalancer
  ports:
    - name: service-port
      port: 80
      targetPort: 8000
  selector:
    app: simple-backend
