apiVersion: v1
kind: Pod
metadata:
  name: k8s-secret-inspect
  labels:
    name: k8s-secret-inspect
spec:
  containers:
    - name: k8s-secret-inspect
      image: ddysher/dns-backend
      volumeMounts:
        - name: kube-registry-keypair
          readOnly: true
          mountPath: /tmp/keypair
  volumes:
    - name: kube-registry-keypair
      secret:
        secretName: kube-registry-keypair
