---
# This is the master playbook which deploys the entire Mesos cluster
# infrastructure on vagrant. Note in hosts file, we simply specify
# Vagrant's private key, instead of the private key in .ssh. To provision
# Mesos cluster, simply run:
# // Bootstrap clusters
# $ vagrant up
# // Use only one fork to not exhaust host machine.
# $ ansible-playbook -i hosts site.yml -f 1

- name: Install common packages
  hosts: all
  sudo: True
  roles:
    - { role: packages }

- name: Deploy zookeeper on mesos master
  hosts: mesos_masters
  sudo: True
  roles:
    - { role: zookeeper }

- name: Deploy and configure mesos master
  hosts: mesos_masters
  sudo: True
  roles:
    - { role: mesos, mesos_install_mode: "master", mesos_ip: "{{ inventory_hostname}}", zookeeper_hostnames: "{{ groups.mesos_masters | join(':' + zookeeper_client_port + ',') }}:{{ zookeeper_client_port }}"}

- name: Deploy and configure mesos slaves
  hosts: mesos_slaves
  sudo: True
  roles:
    - { role: mesos, mesos_install_mode: "slave", mesos_ip: "{{ inventory_hostname}}", zookeeper_hostnames: "{{ groups.mesos_masters | join(':' + zookeeper_client_port + ',') }}:{{ zookeeper_client_port }}"}
