apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simple-backend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: simple-backend
    spec:
      containers:
      - name: simple-backend
        image: ddysher/simple-backend
        ports:
          - containerPort: 8000
