apiVersion: v1
kind: Pod
metadata:
  name: k8s-inspect
  labels:
    name: k8s-inspect
    role: test
spec:
  containers:
  - name: k8s-inspect
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
    image: kube-registry.default.local/k8s-inspect
  restartPolicy: Never
