---
# handlers file for mesos

- name: Restart mesos-master
  sudo: yes
  service: name=mesos-master state=restarted

- name: Restart mesos-slave
  sudo: yes
  service: name=mesos-slave state=restarted
