//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;

var ttypes = require('./master_types');
//HELPER FUNCTIONS AND STRUCTURES

MasterServer_getProjectMeta_args = function(args) {
  this.name = null;
  if (args) {
    if (args.name !== undefined) {
      this.name = args.name;
    }
  }
};
MasterServer_getProjectMeta_args.prototype = {};
MasterServer_getProjectMeta_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.name = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MasterServer_getProjectMeta_args.prototype.write = function(output) {
  output.writeStructBegin('MasterServer_getProjectMeta_args');
  if (this.name !== null && this.name !== undefined) {
    output.writeFieldBegin('name', Thrift.Type.STRING, 1);
    output.writeString(this.name);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MasterServer_getProjectMeta_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
MasterServer_getProjectMeta_result.prototype = {};
MasterServer_getProjectMeta_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.ProjectMeta();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MasterServer_getProjectMeta_result.prototype.write = function(output) {
  output.writeStructBegin('MasterServer_getProjectMeta_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MasterServer_getVersionMeta_args = function(args) {
  this.versionID = null;
  if (args) {
    if (args.versionID !== undefined) {
      this.versionID = args.versionID;
    }
  }
};
MasterServer_getVersionMeta_args.prototype = {};
MasterServer_getVersionMeta_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.versionID = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MasterServer_getVersionMeta_args.prototype.write = function(output) {
  output.writeStructBegin('MasterServer_getVersionMeta_args');
  if (this.versionID !== null && this.versionID !== undefined) {
    output.writeFieldBegin('versionID', Thrift.Type.I32, 2);
    output.writeI32(this.versionID);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MasterServer_getVersionMeta_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
MasterServer_getVersionMeta_result.prototype = {};
MasterServer_getVersionMeta_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.VersionMeta();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MasterServer_getVersionMeta_result.prototype.write = function(output) {
  output.writeStructBegin('MasterServer_getVersionMeta_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MasterServer_getLastestVersionMeta_args = function(args) {
  this.name = null;
  if (args) {
    if (args.name !== undefined) {
      this.name = args.name;
    }
  }
};
MasterServer_getLastestVersionMeta_args.prototype = {};
MasterServer_getLastestVersionMeta_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.name = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MasterServer_getLastestVersionMeta_args.prototype.write = function(output) {
  output.writeStructBegin('MasterServer_getLastestVersionMeta_args');
  if (this.name !== null && this.name !== undefined) {
    output.writeFieldBegin('name', Thrift.Type.STRING, 3);
    output.writeString(this.name);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MasterServer_getLastestVersionMeta_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
MasterServer_getLastestVersionMeta_result.prototype = {};
MasterServer_getLastestVersionMeta_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.VersionMeta();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MasterServer_getLastestVersionMeta_result.prototype.write = function(output) {
  output.writeStructBegin('MasterServer_getLastestVersionMeta_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MasterServerClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this.seqid = 0;
    this._reqs = {};
};
MasterServerClient.prototype = {};
MasterServerClient.prototype.getProjectMeta = function(name, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_getProjectMeta(name);
};

MasterServerClient.prototype.send_getProjectMeta = function(name) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getProjectMeta', Thrift.MessageType.CALL, this.seqid);
  var args = new MasterServer_getProjectMeta_args();
  args.name = name;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

MasterServerClient.prototype.recv_getProjectMeta = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new MasterServer_getProjectMeta_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getProjectMeta failed: unknown result');
};
MasterServerClient.prototype.getVersionMeta = function(versionID, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_getVersionMeta(versionID);
};

MasterServerClient.prototype.send_getVersionMeta = function(versionID) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getVersionMeta', Thrift.MessageType.CALL, this.seqid);
  var args = new MasterServer_getVersionMeta_args();
  args.versionID = versionID;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

MasterServerClient.prototype.recv_getVersionMeta = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new MasterServer_getVersionMeta_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getVersionMeta failed: unknown result');
};
MasterServerClient.prototype.getLastestVersionMeta = function(name, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_getLastestVersionMeta(name);
};

MasterServerClient.prototype.send_getLastestVersionMeta = function(name) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getLastestVersionMeta', Thrift.MessageType.CALL, this.seqid);
  var args = new MasterServer_getLastestVersionMeta_args();
  args.name = name;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

MasterServerClient.prototype.recv_getLastestVersionMeta = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new MasterServer_getLastestVersionMeta_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getLastestVersionMeta failed: unknown result');
};
MasterServerProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
MasterServerProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.Exception, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

MasterServerProcessor.prototype.process_getProjectMeta = function(seqid, input, output) {
  var args = new MasterServer_getProjectMeta_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.getProjectMeta(args.name, function (err, result) {
    var result = new MasterServer_getProjectMeta_result((err != null ? err : {success: result}));
    output.writeMessageBegin("getProjectMeta", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

MasterServerProcessor.prototype.process_getVersionMeta = function(seqid, input, output) {
  var args = new MasterServer_getVersionMeta_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.getVersionMeta(args.versionID, function (err, result) {
    var result = new MasterServer_getVersionMeta_result((err != null ? err : {success: result}));
    output.writeMessageBegin("getVersionMeta", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

MasterServerProcessor.prototype.process_getLastestVersionMeta = function(seqid, input, output) {
  var args = new MasterServer_getLastestVersionMeta_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.getLastestVersionMeta(args.name, function (err, result) {
    var result = new MasterServer_getLastestVersionMeta_result((err != null ? err : {success: result}));
    output.writeMessageBegin("getLastestVersionMeta", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

