apiVersion: v1beta1
id: volume
kind: Pod
desiredState:
  manifest:
    version: v1beta1
    id: storage
    containers:
      - name: redis
        image: redis
        volumeMounts:
          # name must match the volume name below
          - name: redis-persistent-git-storage
            # mount path within the container
            mountPath: /data/redis
    volumes:
      - name: redis-persistent-git-storage
        source:
          gitRepo:
            repository: https://github.com/ddysher/code
