apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: daemonset
  labels:
    version: v1
spec:
  template:
    metadata:
      labels:
        name: daemonset
    spec:
      containers:
      - name: created-from-daemonset
        image: ddysher/simple-backend
      restartPolicy: Always
