apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
  - name: example
    image: index.caicloud.io/caicloud/go-echoserver
    resources:
      limits:
        cpu: 150m
        memory: 150Mi
      requests:
        cpu: 100m
        memory: 100Mi
    volumeMounts:
    - name: storage
      mountPath: /data/data
  volumes:
  - name: storage
    emptyDir: {}
