# ReplicaSet use more general forms of selector. However, the effect is the same,
# i.e. it matches pod-with-label-2.
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: replicaset-1
spec:
  replicas: 1
  # Note selector is more general now.
  selector:
    matchLabels:
      environment: test
  template:
    metadata:
      labels:
        environment: test
    spec:
      containers:
      - name: created-from-replicaset
        image: ddysher/simple-backend
      restartPolicy: Always
