# matchExpressions is the new syntax. Not this replicaset doesn't match any pod.
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: replicaset-2
spec:
  replicas: 1
  selector:
    matchLabels:
      environment: test
    matchExpressions:
      # Valid operators include In, NotIn, Exists, and DoesNotExist.
      - {key: release, operator: Exists}
      - {key: tier, operator: NotIn, values: [backend]}
  template:
    metadata:
      labels:
        environment: test
        release: stable
        tier: frontend
    spec:
      containers:
      - name: created-from-replicaset
        image: ddysher/simple-backend
      restartPolicy: Always
