---
# Tasks for Mesos slave

# == Remove default configs
- name: Remove default mesos configs
  file: state=absent path=/etc/mesos/
  file: state=absent path=/etc/default/mesos/

- name: Remove mesos zk file
  file: state=absent path=/etc/mesos/zk

- name: Remove default mesos slave config
  file: state=absent path=/etc/mesos-slave/
  file: state=absent path=/etc/default/mesos-slave/

# == Recreate config directory
- name: Create default config directory
  sudo: yes
  file: state=directory dest=/etc/mesos

- name: Create default slave config directory
  sudo: yes
  file: state=directory dest=/etc/mesos-slave

# == Set configurations
- name: Disable zookeeper service
  sudo: yes
  copy: content="manual" dest=/etc/init/zookeeper.override mode=0644

- name: Stop zookeeper service
  service: name=zookeeper state=stopped

- name: Set zookeeper url
  sudo: yes
  copy: content="{{ mesos_zookeeper_masters }}" dest=/etc/mesos/zk mode=0644

- name: Set mesos slave hostname
  copy: content="{{ mesos_hostname }}" dest=/etc/mesos-slave/hostname mode=0644
  sudo: yes

- name: Set mesos slave ip
  copy: content="{{mesos_ip }}" dest=/etc/mesos-slave/ip mode=0644
  sudo: yes

- name: Disable mesos master service
  sudo: yes
  copy: content="manual" dest=/etc/init/mesos-master.override mode=0644

- name: Stop mesos master service
  sudo: yes
  service: name=mesos-master state=stopped

- name: Start mesos slave service
  sudo: yes
  service: name=mesos-slave state=restarted
