apiVersion: v1
kind: Pod
metadata:
  name: private-pod
  labels:
    name: private-pod
spec:
  containers:
    - name: ubuntu
      image: ubuntu
  imagePullSecrets:
    - name: caicloud-registry-key
  restartPolicy: Never
