apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-with-two-containers
spec:
  replicas: 1
  selector:
    environment: two-containers
  template:
    metadata:
      labels:
        environment: two-containers
    spec:
      containers:
      - name: container-1
        image: ddysher/pause:2.0
      - name: container-2
        image: ddysher/pause:2.0
      restartPolicy: Always
