# Add one more key/value in selector; similar to rc-with-selector-2, it matches
# pod-with-label-2.
apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-with-selector-2
spec:
  replicas: 1
  selector:
    environment: test
    tier: backend
  template:
    metadata:
      labels:
        environment: test
        tier: backend
    spec:
      containers:
      - name: created-from-rc
        image: ddysher/simple-backend
      restartPolicy: Always
