apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: replicaset-1
spec:
  replicas: 1
  selector:
    matchLabels:
      environment: prod
  template:
    metadata:
      labels:
        environment: prod
    spec:
      containers:
      - name: created-from-replicaset
        image: nginx
